# Generated by Django 5.1.1 on 2024-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_application_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
