# Generated by Django 5.1.1 on 2024-12-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_opportunity_completed_opportunity_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
