# Generated by Django 5.1.1 on 2024-12-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_application_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied',
            new_name='apply',
        ),
    ]
