# Generated by Django 5.1.1 on 2024-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_opportunity_feedback_application_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='feedback',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
