# Generated by Django 5.1.1 on 2024-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_application_feedback_opportunity_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
