# Generated by Django 5.1.1 on 2024-12-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_opportunity_latitude_opportunity_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='apply',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='apply',
            field=models.BooleanField(default=False),
        ),
    ]
