# Generated by Django 5.1.1 on 2024-12-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_application_apply_opportunity_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='apply',
        ),
        migrations.AddField(
            model_name='application',
            name='apply',
            field=models.BooleanField(default=False),
        ),
    ]
