# Generated by Django 5.1.1 on 2024-12-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_opportunity_apply_application_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='apply',
        ),
    ]
